services:
  vending-machine:
    container_name: vending-machine
    build:
      context: .
      dockerfile: docker/vending-machine/Dockerfile
      target: dev
    volumes:
      - ./vending-machine:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./vending-machine/.env.development.local
    depends_on:
      - vending-machine-api

  vending-machine-api:
    container_name: vending-machine-api
    build:
      context: .
      dockerfile: docker/vending-machine-api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./vending-machine-api/.env.development.local
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0
    restart: always
    container_name: database
    env_file:
      - ./vending-machine-api/.env.development.local
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
